### ISSUE TITLE
Strange Toolbar Appeared at the top

### ISSUE THREAD

**Issue by lhy0403** [aliyuchang33/Hv2ray#1]
# Description
- Using the latest v0.0.3 version...
- Once the HV2ray is started, there is a toolbar, which has a tiny height, appearing at the top of the main Application Window.

# Steps to reproduce
- Open the HV2Ray.
- That toolbar is there, a handle can be seen on the top-left of the window

# Possible Workaround
- None, as that's not affecting the usability

# How to Fix
- I don't know

**Comment by lhy0403** [comment]
EDIT: That could be the `mainToolBar` defined in `https://github.com/aliyuchang33/Hv2ray/blob/master/src/mainwindow.ui#L135`, but currently has no functions.

**Comment by aliyuchang33** [comment]
It is left there because it may be used in the future. Now I defined some push button to perfrom "start, stop" and so on actions. They may be moved to the toolbar. Thanks for your contribution.
