### ISSUE TITLE
Pyhont.h 不存在

### ISSUE THREAD

**Issue by Wap8CN** [aliyuchang33/Hv2ray#9]
大佬，我下载了release的source code编译提示没有Python.h头文件。
本来想在贴吧回复你，可惜你设置了权限。。

**Comment by aliyuchang33** [comment]
你是ArchLinux么，Arch没有3.6的包了，把Hv2ray.pro里边的3.6依赖改成3.7就好了。

**Comment by Wap8CN** [comment]
@aliyuchang33  我是ubuntu16.04，我自己的cmd环境是python3.6，我开始用编译好的zip提示我没有python3.7m的lib，于是我自己编译源码。Hv2ray.pro里的3.7m和3.6m我都试了，都报错没有Python.h

**Comment by lhy0403** [comment]
你是不是没有安装 python。。。？

**Comment by lhy0403** [comment]
请检查 INCLUDEPATH 和  你 locate Python.h 后的结果

**Comment by Wap8CN** [comment]
@lhy0403   Soga，对对对。。忘记检查路径是否一致了，我只是直接把3.7m改成3.6了，等下试一下。估计是这个问题，多谢多谢。
